### ISSUE TITLE
New login link again

### ISSUE THREAD

**Issue by mpoqq** [digitalshow/IliasDownload#1]
I think the login link change again.

Old: ilias.php?lang=de&client_id=Uni_Stuttgart&cmd=post&cmdClass=ilstartupgui&cmdNode=v**a**&baseClass=ilStartUpGUI&rtoken=

New: ilias.php?lang=de&client_id=Uni_Stuttgart&cmd=post&cmdClass=ilstartupgui&cmdNode=v**b**&baseClass=ilStartUpGUI&rtoken=

If you don't want to change the link every month you can extract that link from the login page like this:
`curl -v --silent  "https://ilias3.uni-stuttgart.de/login.php?target=&client_id=Uni_Stuttgart&cmd=force_login&lang=de" 2>&1 |  sed -n '/name="formlogin"/,/action/p' | sed -n 2p | sed 's/^action="\([^"]*\).*/\1/' | sed 's/&amp;/\&/g'
`

**Comment by digitalshow** [comment]
Thank you for your suggestion!
